/* The following code was generated by JFlex 1.4.3 on 13-10-7 上午9:07 */

// Copyright (c) 2013, Boilit. All Rights Reserved.

package org.boilit.bsl.core;

import org.boilit.cup.Symbol;
import org.boilit.cup.Scanner;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 13-10-7 上午9:07 from the specification file
 * <tt>D:/W04WorkSpace/Maven001/bsl/src/analyzer/Lexer.jflex</tt>
 */
public class Lexer implements ITokens, Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 4;
  public static final int YYINITIAL = 0;
  public static final int YYSTATEMENT = 2;
  public static final int END_OF_FILE = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\26\1\2\1\0\1\26\1\1\22\0\1\26\1\32\1\76"+
    "\1\57\1\37\1\70\1\65\1\77\1\74\1\75\1\30\1\22\1\62"+
    "\1\33\1\20\1\27\4\100\4\101\2\14\1\61\1\63\1\31\1\67"+
    "\1\36\1\64\1\60\1\25\1\15\1\25\1\24\1\21\1\23\5\25"+
    "\1\17\6\25\1\16\7\25\1\34\1\41\1\35\1\71\1\25\1\0"+
    "\1\12\1\53\1\43\1\44\1\10\1\11\1\47\1\45\1\42\1\25"+
    "\1\54\1\5\1\56\1\3\1\46\1\51\1\25\1\7\1\13\1\6"+
    "\1\4\1\50\1\55\1\52\2\25\1\40\1\66\1\73\1\72\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\6\1\1\2\2\3\7\4\1\5\1\6\1\7"+
    "\1\3\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\5\4\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\1\2\42\1\0\1\43"+
    "\3\0\10\4\1\44\1\0\1\45\1\46\1\47\1\0"+
    "\1\50\1\51\1\52\2\0\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\0\1\62\1\63\1\4\1\64"+
    "\5\4\1\65\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\1\74\1\75\1\76\1\77\1\100\1\101\1\42\1\102"+
    "\2\103\1\0\7\4\1\104\5\0\1\105\1\0\1\106"+
    "\1\107\1\4\1\110\1\111\1\4\1\112\1\4\1\113"+
    "\1\114\1\103\1\0\1\115\1\116\1\117\1\120\1\121"+
    "\1\122\1\3\1\123\1\124\3\4\1\125\1\4\1\126"+
    "\1\127\1\4\1\130";

  private static int [] zzUnpackAction() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\204\0\306\0\u0108\0\u014a\0\u018c\0\u01ce"+
    "\0\u0210\0\u0252\0\u0108\0\u0294\0\u02d6\0\u0318\0\u035a\0\u039c"+
    "\0\u03de\0\u0420\0\u0462\0\u04a4\0\u04e6\0\u0108\0\u0528\0\u0108"+
    "\0\u056a\0\u05ac\0\u05ee\0\u0630\0\u0672\0\u0108\0\u06b4\0\u06f6"+
    "\0\u0108\0\u0738\0\u077a\0\u07bc\0\u07fe\0\u0840\0\u0108\0\u0108"+
    "\0\u0108\0\u0108\0\u0108\0\u0882\0\u08c4\0\u0906\0\u0948\0\u098a"+
    "\0\u09cc\0\u0108\0\u0108\0\u0108\0\u0108\0\u0108\0\u0108\0\u0a0e"+
    "\0\u0a50\0\u0108\0\u0a92\0\u0108\0\u01ce\0\u0210\0\u0252\0\u0ad4"+
    "\0\u0b16\0\u0b58\0\u0b9a\0\u0bdc\0\u0c1e\0\u0c60\0\u0ca2\0\u0108"+
    "\0\u0ce4\0\u0108\0\u0108\0\u0108\0\u0d26\0\u0108\0\u0108\0\u0108"+
    "\0\u0d68\0\u0daa\0\u0108\0\u0108\0\u0dec\0\u0108\0\u0108\0\u0108"+
    "\0\u0108\0\u0e2e\0\u0e70\0\u0108\0\u0eb2\0\u035a\0\u0ef4\0\u0f36"+
    "\0\u0f78\0\u0fba\0\u0ffc\0\u0108\0\u103e\0\u0108\0\u1080\0\u0108"+
    "\0\u0108\0\u0108\0\u0108\0\u0108\0\u0108\0\u0108\0\u0108\0\u0108"+
    "\0\u10c2\0\u0108\0\u1104\0\u1146\0\u1188\0\u11ca\0\u120c\0\u124e"+
    "\0\u1290\0\u12d2\0\u1314\0\u1356\0\u035a\0\u1398\0\u13da\0\u141c"+
    "\0\u0294\0\u145e\0\u0108\0\u14a0\0\u14e2\0\u0108\0\u1524\0\u035a"+
    "\0\u035a\0\u1566\0\u035a\0\u15a8\0\u0108\0\u0108\0\u0108\0\u15ea"+
    "\0\u035a\0\u035a\0\u035a\0\u035a\0\u035a\0\u035a\0\u0daa\0\u0108"+
    "\0\u0108\0\u162c\0\u166e\0\u16b0\0\u0108\0\u16f2\0\u035a\0\u035a"+
    "\0\u1734\0\u035a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\26\5\1\10\5\5\1\11\1\5"+
    "\1\12\40\5\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\17\1\22\1\23\1\24\1\17\1\25\3\17"+
    "\1\26\1\17\1\27\3\17\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\17\1\41\1\13"+
    "\1\42\5\17\1\43\1\44\1\17\1\45\2\17\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\65\1\66"+
    "\1\67\2\25\41\70\1\71\34\70\2\72\2\70\102\13"+
    "\104\0\1\5\100\0\1\5\132\0\1\73\107\0\1\74"+
    "\72\0\1\75\5\0\1\76\1\0\1\77\42\0\1\30"+
    "\100\0\1\30\103\0\1\17\1\100\3\17\1\101\7\17"+
    "\1\0\1\17\1\0\3\17\11\0\1\17\2\0\15\17"+
    "\21\0\2\17\3\0\15\17\1\0\1\17\1\0\3\17"+
    "\11\0\1\17\2\0\15\17\21\0\2\17\3\0\15\17"+
    "\1\0\1\17\1\0\3\17\11\0\1\17\2\0\4\17"+
    "\1\102\10\17\21\0\2\17\3\0\4\17\1\103\10\17"+
    "\1\0\1\17\1\0\3\17\11\0\1\17\2\0\15\17"+
    "\21\0\2\17\3\0\2\17\1\104\12\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\1\17\1\105\13\17"+
    "\21\0\2\17\3\0\7\17\1\106\5\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\15\17\21\0\2\17"+
    "\3\0\4\17\1\107\10\17\1\0\1\17\1\0\3\17"+
    "\11\0\1\17\2\0\15\17\21\0\2\17\5\0\1\110"+
    "\2\0\1\111\1\112\1\0\1\113\1\25\1\114\1\113"+
    "\1\110\1\115\1\111\1\0\1\112\1\116\17\0\1\116"+
    "\6\0\1\114\24\0\2\25\22\0\1\117\44\0\1\120"+
    "\41\0\1\121\1\122\36\0\1\123\101\0\1\124\43\0"+
    "\1\125\35\0\1\126\101\0\1\127\45\0\1\130\33\0"+
    "\1\131\45\0\1\132\104\0\1\133\30\0\1\134\15\0"+
    "\1\135\5\17\1\136\6\17\1\0\1\17\1\0\3\17"+
    "\11\0\1\17\2\0\15\17\21\0\2\17\3\0\7\17"+
    "\1\137\5\17\1\0\1\17\1\0\3\17\11\0\1\17"+
    "\2\0\15\17\21\0\2\17\3\0\15\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\4\17\1\140\10\17"+
    "\21\0\2\17\3\0\4\17\1\141\10\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\7\17\1\142\5\17"+
    "\21\0\2\17\3\0\5\17\1\143\7\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\15\17\21\0\2\17"+
    "\61\0\1\144\105\0\1\145\1\0\1\146\100\0\1\147"+
    "\1\150\101\0\1\151\101\0\1\152\101\0\1\153\12\0"+
    "\41\70\1\0\34\70\2\0\2\70\2\154\1\0\1\155"+
    "\2\154\1\156\1\157\1\154\1\160\27\154\1\161\11\154"+
    "\1\162\22\154\2\72\1\163\1\164\33\0\1\165\51\0"+
    "\2\17\1\166\12\17\1\0\1\17\1\0\3\17\11\0"+
    "\1\17\2\0\15\17\21\0\2\17\3\0\15\17\1\0"+
    "\1\17\1\0\3\17\11\0\1\17\2\0\10\17\1\167"+
    "\4\17\21\0\2\17\3\0\15\17\1\0\1\17\1\0"+
    "\3\17\11\0\1\17\2\0\4\17\1\170\10\17\21\0"+
    "\2\17\3\0\1\17\1\171\13\17\1\0\1\17\1\0"+
    "\3\17\11\0\1\17\2\0\15\17\21\0\2\17\3\0"+
    "\10\17\1\172\4\17\1\0\1\17\1\0\3\17\11\0"+
    "\1\17\2\0\15\17\21\0\2\17\3\0\15\17\1\0"+
    "\1\17\1\0\3\17\11\0\1\17\2\0\3\17\1\173"+
    "\11\17\21\0\2\17\3\0\2\17\1\174\12\17\1\0"+
    "\1\17\1\0\3\17\11\0\1\17\2\0\15\17\21\0"+
    "\2\17\3\0\15\17\1\0\1\17\1\0\3\17\11\0"+
    "\1\17\2\0\5\17\1\175\7\17\21\0\2\17\14\0"+
    "\1\176\5\0\1\177\10\0\1\177\44\0\2\176\14\0"+
    "\1\200\63\0\2\200\1\121\1\201\1\30\77\121\2\122"+
    "\1\0\25\122\1\202\51\122\67\0\1\203\45\0\1\204"+
    "\104\0\1\205\30\0\1\206\15\0\15\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\1\17\1\207\13\17"+
    "\21\0\2\17\3\0\4\17\1\210\10\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\15\17\21\0\2\17"+
    "\3\0\15\17\1\0\1\17\1\0\3\17\11\0\1\17"+
    "\2\0\13\17\1\211\1\17\21\0\2\17\3\0\5\17"+
    "\1\212\7\17\1\0\1\17\1\0\3\17\11\0\1\17"+
    "\2\0\15\17\21\0\2\17\3\0\15\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\13\17\1\213\1\17"+
    "\21\0\2\17\3\0\4\17\1\214\10\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\15\17\21\0\2\17"+
    "\67\0\1\215\101\0\1\216\53\0\1\161\34\0\2\72"+
    "\102\0\2\164\100\0\2\217\33\0\1\220\51\0\2\17"+
    "\1\221\12\17\1\0\1\17\1\0\3\17\11\0\1\17"+
    "\2\0\15\17\21\0\2\17\3\0\3\17\1\222\11\17"+
    "\1\0\1\17\1\0\3\17\11\0\1\17\2\0\15\17"+
    "\21\0\2\17\3\0\15\17\1\0\1\17\1\0\3\17"+
    "\11\0\1\17\2\0\7\17\1\223\5\17\21\0\2\17"+
    "\3\0\5\17\1\224\7\17\1\0\1\17\1\0\3\17"+
    "\11\0\1\17\2\0\15\17\21\0\2\17\3\0\5\17"+
    "\1\225\7\17\1\0\1\17\1\0\3\17\11\0\1\17"+
    "\2\0\15\17\21\0\2\17\3\0\15\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\4\17\1\226\10\17"+
    "\21\0\2\17\3\0\10\17\1\171\4\17\1\0\1\17"+
    "\1\0\3\17\11\0\1\17\2\0\15\17\21\0\2\17"+
    "\11\0\1\112\2\0\1\176\6\0\1\112\1\116\17\0"+
    "\1\116\33\0\2\176\14\0\1\176\63\0\2\176\10\0"+
    "\1\111\1\112\2\0\1\200\4\0\1\111\1\0\1\112"+
    "\1\116\17\0\1\116\33\0\2\200\2\122\1\0\24\122"+
    "\1\227\1\202\51\122\36\0\1\230\132\0\1\231\15\0"+
    "\2\17\1\232\12\17\1\0\1\17\1\0\3\17\11\0"+
    "\1\17\2\0\15\17\21\0\2\17\3\0\7\17\1\233"+
    "\5\17\1\0\1\17\1\0\3\17\11\0\1\17\2\0"+
    "\15\17\21\0\2\17\3\0\15\17\1\0\1\17\1\0"+
    "\3\17\11\0\1\17\2\0\5\17\1\234\7\17\21\0"+
    "\2\17\34\0\1\235\50\0\1\17\1\236\13\17\1\0"+
    "\1\17\1\0\3\17\11\0\1\17\2\0\15\17\21\0"+
    "\2\17\3\0\15\17\1\0\1\17\1\0\3\17\11\0"+
    "\1\17\2\0\12\17\1\237\2\17\21\0\2\17\3\0"+
    "\5\17\1\240\7\17\1\0\1\17\1\0\3\17\11\0"+
    "\1\17\2\0\15\17\21\0\2\17\3\0\15\17\1\0"+
    "\1\17\1\0\3\17\11\0\1\17\2\0\2\17\1\241"+
    "\12\17\21\0\2\17\3\0\5\17\1\242\7\17\1\0"+
    "\1\17\1\0\3\17\11\0\1\17\2\0\15\17\21\0"+
    "\2\17";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6006];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\5\1\1\11\12\1\1\11\1\1\1\11"+
    "\5\1\1\11\2\1\1\11\5\1\5\11\6\1\6\11"+
    "\2\1\1\11\1\0\1\11\3\0\10\1\1\11\1\0"+
    "\3\11\1\0\3\11\2\0\2\11\1\1\4\11\1\0"+
    "\1\1\1\11\7\1\1\11\1\1\1\11\1\1\11\11"+
    "\1\1\1\11\2\1\1\0\10\1\5\0\1\11\1\0"+
    "\1\1\1\11\6\1\3\11\1\0\7\1\2\11\3\1"+
    "\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	public boolean holded = false;
	public char wrapper = 0;
	private int line = 0;
	private int column = 0;
	private LexerBuffer buffer = new LexerBuffer(256);
	
	public int getLine() {
		return yyline + 1;
	}
	
	public int getColumn() {
		return yycolumn + 1;
	}

    public final String yytext(int endOffset) {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead + endOffset);
    }

    public final String yytext(int startOffset, int endOffset) {
        return new String(zzBuffer, zzStartRead + startOffset, zzMarkedPos - zzStartRead + endOffset);
    }
	
	private void append() {
		buffer.append(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
	}
	
	private void append(char c) {
		buffer.append(c);
	}
	
	private void append(char c, int repeat) {
		if(repeat == 1) {
			buffer.append(c);
			return;
		}
		char[] chars = new char[repeat];
		for(int i=0; i < repeat; i++) { 
			chars[i] = c;
		}
		buffer.append(chars);
	}

	private void append(String string) {
		buffer.append(string);
	}

	private void delCodeLineEscape() {
		buffer.delCodeLineEscape();
	}
	
	private String pop() {
		String chars = buffer.toString();
		buffer.clear();
		return chars;
	}
	
	private void reset() {
		buffer.clear();
		line = yyline;
		column = yycolumn;
	}
	
	private Symbol symbol(int sym) {
		return new Symbol(sym, yyline + 1, yycolumn + 1, sym);
	}
	
	private Symbol symbol(int sym, Object value) {
		return new Symbol(sym, yyline + 1, yycolumn + 1, value);
	}
	
	private Symbol symbol(int sym, int line, int column, Object value) {
		return new Symbol(sym, line, column, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 160) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 28: 
          { return symbol(BIT_NOT);
          }
        case 89: break;
        case 72: 
          { return symbol(VAR);
          }
        case 90: break;
        case 79: 
          { return symbol(LOOP);
          }
        case 91: break;
        case 74: 
          { return symbol(BPW);
          }
        case 92: break;
        case 82: 
          { return symbol(ECHO);
          }
        case 93: break;
        case 53: 
          { return symbol(QUESTION_COLON);
          }
        case 94: break;
        case 70: 
          { return symbol(BIT_ZRM);
          }
        case 95: break;
        case 9: 
          { return symbol(NUM_MUL);
          }
        case 96: break;
        case 62: 
          { append('\n');
          }
        case 97: break;
        case 56: 
          { return symbol(LGC_OR);
          }
        case 98: break;
        case 58: 
          { return symbol(LGC_CEE);
          }
        case 99: break;
        case 31: 
          { return symbol(PRN_RIGHT);
          }
        case 100: break;
        case 8: 
          { return symbol(NUM_DIV);
          }
        case 101: break;
        case 7: 
          { return symbol(NUM_ADD);
          }
        case 102: break;
        case 43: 
          { return symbol(NUM_DIV_ASSIGN);
          }
        case 103: break;
        case 29: 
          { if(!holded) {return symbol(BRC_RIGHT);} else { yybegin(YYINITIAL); holded=false; return symbol(HOLD_TAIL); }
          }
        case 104: break;
        case 51: 
          { return symbol(LGC_CGE);
          }
        case 105: break;
        case 59: 
          { return symbol(NUM_MOD_ASSIGN);
          }
        case 106: break;
        case 26: 
          { return symbol(NUM_MOD);
          }
        case 107: break;
        case 64: 
          { append('\r');
          }
        case 108: break;
        case 41: 
          { return symbol(NUM_ADD1);
          }
        case 109: break;
        case 21: 
          { return symbol(SEMI);
          }
        case 110: break;
        case 27: 
          { return symbol(BIT_XOR);
          }
        case 111: break;
        case 14: 
          { return symbol(BRK_RIGHT);
          }
        case 112: break;
        case 16: 
          { return symbol(BRC_LEFT);
          }
        case 113: break;
        case 57: 
          { return symbol(BIT_OR_ASSIGN);
          }
        case 114: break;
        case 1: 
          { append();
          }
        case 115: break;
        case 63: 
          { append('\t');
          }
        case 116: break;
        case 12: 
          { return symbol(NUM_SUB);
          }
        case 117: break;
        case 36: 
          { return symbol(LONG, Long.parseLong(yytext(-1)));
          }
        case 118: break;
        case 46: 
          { return symbol(LGC_CLE);
          }
        case 119: break;
        case 77: 
          { return symbol(NULL);
          }
        case 120: break;
        case 47: 
          { return symbol(LGC_CNE);
          }
        case 121: break;
        case 39: 
          { return symbol(BYTE, Byte.parseByte(yytext(-1)));
          }
        case 122: break;
        case 78: 
          { return symbol(NEXT);
          }
        case 123: break;
        case 4: 
          { return symbol(LABEL, yytext());
          }
        case 124: break;
        case 33: 
          { wrapper='\'';
	    yybegin(STRING);
	    reset();
          }
        case 125: break;
        case 25: 
          { return symbol(ASSIGN);
          }
        case 126: break;
        case 69: 
          { return symbol(BIT_LM_ASSIGN);
          }
        case 127: break;
        case 32: 
          { wrapper='"';
	    yybegin(STRING);
	    reset();
          }
        case 128: break;
        case 2: 
          { throw new RuntimeException("Illegal character \"" + yytext() + "\" at line " + yyline + ", column " + yycolumn);
          }
        case 129: break;
        case 87: 
          { return symbol(MERGE);
          }
        case 130: break;
        case 37: 
          { return symbol(FLOAT, Float.parseFloat(yytext(-1)));
          }
        case 131: break;
        case 55: 
          { return symbol(BIT_AND_ASSIGN);
          }
        case 132: break;
        case 22: 
          { return symbol(QUESTION);
          }
        case 133: break;
        case 52: 
          { return symbol(IF);
          }
        case 134: break;
        case 5: 
          { return symbol(INTEGER, Integer.parseInt(yytext()));
          }
        case 135: break;
        case 88: 
          { return symbol(INCLUDE);
          }
        case 136: break;
        case 86: 
          { return symbol(BREAK);
          }
        case 137: break;
        case 38: 
          { return symbol(SHORT, Short.parseShort(yytext(-1)));
          }
        case 138: break;
        case 85: 
          { int n = yylength() -5;
		append('\\',n/2);
		if(n%2 == 0){
		    holded = false;
		    delCodeLineEscape();
		    yybegin(YYSTATEMENT);
		    return symbol(TEXT, line, column, pop());
		} else {
		    append("<!--[");
		}
          }
        case 139: break;
        case 76: 
          { return symbol(LGC_OR_ASSIGN);
          }
        case 140: break;
        case 61: 
          { throw new RuntimeException("Illegal escape sequence \"" + yytext() + "\"");
          }
        case 141: break;
        case 44: 
          { return symbol(NUM_MUL_ASSIGN);
          }
        case 142: break;
        case 15: 
          { return symbol(LGC_CGT);
          }
        case 143: break;
        case 24: 
          { return symbol(BIT_OR);
          }
        case 144: break;
        case 17: 
          { return symbol(WELL);
          }
        case 145: break;
        case 40: 
          { return symbol(DOUBLE, Double.parseDouble(yytext(-1)));
          }
        case 146: break;
        case 60: 
          { return symbol(BIT_XOR_ASSIGN);
          }
        case 147: break;
        case 83: 
          { yybegin(YYINITIAL);
          }
        case 148: break;
        case 54: 
          { return symbol(LGC_AND);
          }
        case 149: break;
        case 6: 
          { return symbol(DOT);
          }
        case 150: break;
        case 75: 
          { return symbol(LGC_AND_ASSIGN);
          }
        case 151: break;
        case 84: 
          { return symbol(BIT_ZRM_ASSIGN);
          }
        case 152: break;
        case 71: 
          { return symbol(BIT_RM_ASSIGN);
          }
        case 153: break;
        case 48: 
          { return symbol(NUM_SUB1);
          }
        case 154: break;
        case 66: 
          { append('\b');
          }
        case 155: break;
        case 45: 
          { return symbol(BIT_LM);
          }
        case 156: break;
        case 68: 
          { return symbol(ARG);
          }
        case 157: break;
        case 10: 
          { return symbol(LGC_CLT);
          }
        case 158: break;
        case 11: 
          { return symbol(LGC_NOT);
          }
        case 159: break;
        case 19: 
          { return symbol(COLON);
          }
        case 160: break;
        case 30: 
          { return symbol(PRN_LEFT);
          }
        case 161: break;
        case 49: 
          { return symbol(NUM_SUB_ASSIGN);
          }
        case 162: break;
        case 35: 
          { int n = yylength()-2;
		append('\\',n/2);
		if(n%2 == 0){
		    holded = true;
		    yybegin(YYSTATEMENT);
		    return symbol(TEXT, line, column, pop());
		} else {
		    append("${");
		}
          }
        case 163: break;
        case 65: 
          { append('\f');
          }
        case 164: break;
        case 3: 
          { /* ignore */
          }
        case 165: break;
        case 34: 
          { int n = yylength()-1;
        append('\\',n/2);
        char c = yycharat(n);
        if(wrapper==c && n%2 == 0){
            yybegin(YYSTATEMENT);
            return symbol(CHARS, line, column, pop());
        } else {
            append(c);
        }
          }
        case 166: break;
        case 18: 
          { return symbol(AT);
          }
        case 167: break;
        case 42: 
          { return symbol(NUM_ADD_ASSIGN);
          }
        case 168: break;
        case 67: 
          { append((char) Integer.parseInt(yytext(1,0),8));
          }
        case 169: break;
        case 80: 
          { return symbol(BOOL, Boolean.parseBoolean(yytext()));
          }
        case 170: break;
        case 50: 
          { return symbol(BIT_RM);
          }
        case 171: break;
        case 23: 
          { return symbol(BIT_AND);
          }
        case 172: break;
        case 81: 
          { return symbol(ELSE);
          }
        case 173: break;
        case 20: 
          { return symbol(COMMA);
          }
        case 174: break;
        case 13: 
          { return symbol(BRK_LEFT);
          }
        case 175: break;
        case 73: 
          { return symbol(NUM_POW);
          }
        case 176: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              yybegin(END_OF_FILE);
		return symbol(TEXT, line, column, pop());
            }
            case 163: break;
            case END_OF_FILE: {
              return symbol(EOF);
            }
            case 164: break;
            default:
              {
                return symbol(EOF);
              }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
